// Generated by scripts/extract-reading-room-assets-sam2.py

import badgesBadge30Chapters from './badges/badge_30_chapters.png';
import badgesBadge7Days from './badges/badge_7_days.png';
import badgesBadgeExplorer from './badges/badge_explorer.png';
import badgesBadgeLocked from './badges/badge_locked.png';
import badgesBadgeReadStart from './badges/badge_read_start.png';
import cardsReadingCardGenesis from './cards/reading_card_genesis.png';
import coursesCourse180Hills from './courses/course_180_hills.png';
import coursesCourse365Landscape from './courses/course_365_landscape.png';
import coursesCourseGospels30Purple from './courses/course_gospels30_purple.png';
import coursesCourseNt100Night from './courses/course_nt100_night.png';
import decorationsFlowerSmall from './decorations/flower_small.png';
import decorationsLavenderSprig from './decorations/lavender_sprig.png';
import decorationsLeafScatter from './decorations/leaf_scatter.png';
import decorationsLeafSprig01 from './decorations/leaf_sprig_01.png';
import decorationsLeafSprig02 from './decorations/leaf_sprig_02.png';
import decorationsLeafSprig03 from './decorations/leaf_sprig_03.png';
import decorationsLeafSprig04 from './decorations/leaf_sprig_04.png';
import decorationsSparkles from './decorations/sparkles.png';
import iconsAchievementBadge from './icons/achievement_badge.png';
import iconsBackArrow from './icons/back_arrow.png';
import iconsBell from './icons/bell.png';
import iconsBibleClosed from './icons/bible_closed.png';
import iconsBibleOpen from './icons/bible_open.png';
import iconsBookmark from './icons/bookmark.png';
import iconsCalendar from './icons/calendar.png';
import iconsCheckSelected from './icons/check_selected.png';
import iconsCheckUnselected from './icons/check_unselected.png';
import iconsChevronLeft from './icons/chevron_left.png';
import iconsClock from './icons/clock.png';
import iconsClose from './icons/close.png';
import iconsCloudIcon from './icons/cloud_icon.png';
import iconsCompletedDay from './icons/completed_day.png';
import iconsCourseList from './icons/course_list.png';
import iconsCrown365 from './icons/crown_365.png';
import iconsDownload from './icons/download.png';
import iconsDroplet from './icons/droplet.png';
import iconsEllipsis from './icons/ellipsis.png';
import iconsFlame from './icons/flame.png';
import iconsFlowerIcon from './icons/flower_icon.png';
import iconsGift from './icons/gift.png';
import iconsHeartLike from './icons/heart_like.png';
import iconsHelp from './icons/help.png';
import iconsIncompleteDay from './icons/incomplete_day.png';
import iconsInfo from './icons/info.png';
import iconsLeafLarge from './icons/leaf_large.png';
import iconsLeafSmall from './icons/leaf_small.png';
import iconsLock from './icons/lock.png';
import iconsMenu from './icons/menu.png';
import iconsMissionFlag from './icons/mission_flag.png';
import iconsNavHome from './icons/nav_home.png';
import iconsNavMore from './icons/nav_more.png';
import iconsNavMyCourse from './icons/nav_my_course.png';
import iconsNavRecommendedCourse from './icons/nav_recommended_course.png';
import iconsNavRecords from './icons/nav_records.png';
import iconsNextChevron from './icons/next_chevron.png';
import iconsPlusCircle from './icons/plus_circle.png';
import iconsProgressRing from './icons/progress_ring.png';
import iconsSettings from './icons/settings.png';
import iconsShare from './icons/share.png';
import iconsSparkleIcon from './icons/sparkle_icon.png';
import iconsSpecialReward from './icons/special_reward.png';
import iconsTag from './icons/tag.png';
import illustrationsBibleGold from './illustrations/bible_gold.png';
import illustrationsBibleGreen from './illustrations/bible_green.png';
import illustrationsBiblePurple from './illustrations/bible_purple.png';
import illustrationsCalendar30 from './illustrations/calendar_30.png';
import illustrationsOpenBibleLeaf from './illustrations/open_bible_leaf.png';
import illustrationsPointDroplet from './illustrations/point_droplet.png';
import illustrationsPointJar from './illustrations/point_jar.png';
import illustrationsSproutCharacter from './illustrations/sprout_character.png';
import illustrationsStreakFlame from './illustrations/streak_flame.png';
import rewardsRewardCrown from './rewards/reward_crown.png';
import rewardsRewardMedal from './rewards/reward_medal.png';
import rewardsRewardShield from './rewards/reward_shield.png';

export const badgesAssets = {
  badge30Chapters: badgesBadge30Chapters,
  badge7Days: badgesBadge7Days,
  badgeExplorer: badgesBadgeExplorer,
  badgeLocked: badgesBadgeLocked,
  badgeReadStart: badgesBadgeReadStart,
};

export const cardsAssets = {
  readingCardGenesis: cardsReadingCardGenesis,
};

export const coursesAssets = {
  course180Hills: coursesCourse180Hills,
  course365Landscape: coursesCourse365Landscape,
  courseGospels30Purple: coursesCourseGospels30Purple,
  courseNt100Night: coursesCourseNt100Night,
};

export const decorationsAssets = {
  flowerSmall: decorationsFlowerSmall,
  lavenderSprig: decorationsLavenderSprig,
  leafScatter: decorationsLeafScatter,
  leafSprig01: decorationsLeafSprig01,
  leafSprig02: decorationsLeafSprig02,
  leafSprig03: decorationsLeafSprig03,
  leafSprig04: decorationsLeafSprig04,
  sparkles: decorationsSparkles,
};

export const iconsAssets = {
  achievementBadge: iconsAchievementBadge,
  backArrow: iconsBackArrow,
  bell: iconsBell,
  bibleClosed: iconsBibleClosed,
  bibleOpen: iconsBibleOpen,
  bookmark: iconsBookmark,
  calendar: iconsCalendar,
  checkSelected: iconsCheckSelected,
  checkUnselected: iconsCheckUnselected,
  chevronLeft: iconsChevronLeft,
  clock: iconsClock,
  close: iconsClose,
  cloudIcon: iconsCloudIcon,
  completedDay: iconsCompletedDay,
  courseList: iconsCourseList,
  crown365: iconsCrown365,
  download: iconsDownload,
  droplet: iconsDroplet,
  ellipsis: iconsEllipsis,
  flame: iconsFlame,
  flowerIcon: iconsFlowerIcon,
  gift: iconsGift,
  heartLike: iconsHeartLike,
  help: iconsHelp,
  incompleteDay: iconsIncompleteDay,
  info: iconsInfo,
  leafLarge: iconsLeafLarge,
  leafSmall: iconsLeafSmall,
  lock: iconsLock,
  menu: iconsMenu,
  missionFlag: iconsMissionFlag,
  navHome: iconsNavHome,
  navMore: iconsNavMore,
  navMyCourse: iconsNavMyCourse,
  navRecommendedCourse: iconsNavRecommendedCourse,
  navRecords: iconsNavRecords,
  nextChevron: iconsNextChevron,
  plusCircle: iconsPlusCircle,
  progressRing: iconsProgressRing,
  settings: iconsSettings,
  share: iconsShare,
  sparkleIcon: iconsSparkleIcon,
  specialReward: iconsSpecialReward,
  tag: iconsTag,
};

export const illustrationsAssets = {
  bibleGold: illustrationsBibleGold,
  bibleGreen: illustrationsBibleGreen,
  biblePurple: illustrationsBiblePurple,
  calendar30: illustrationsCalendar30,
  openBibleLeaf: illustrationsOpenBibleLeaf,
  pointDroplet: illustrationsPointDroplet,
  pointJar: illustrationsPointJar,
  sproutCharacter: illustrationsSproutCharacter,
  streakFlame: illustrationsStreakFlame,
};

export const rewardsAssets = {
  rewardCrown: rewardsRewardCrown,
  rewardMedal: rewardsRewardMedal,
  rewardShield: rewardsRewardShield,
};
